### ISSUE TITLE
Give draw methods the possibility to return ggplot2 objects or data.frame

### ISSUE THREAD

**Issue by singmann** [gavinsimpson/gratia#44] opened 2019-06-06 21:00 UTC
I have a suggestion for a rather small change to the `draw` methods. Specifically, the current code does not really allow a further customization of the returned plots, as they are wrapped into a `plot_grid` call (in line with the documentation). I think it would be great if instead there would be the option to return a `ggplot2` object in some cases so one can actually customize the plot further. The main idea is to use the current `draw` method as the basis for further developments.

I can see three different possibilities:

1. If only one plot is produced returned always return a `ggplot2` object and skip the call to `plot_grid`. This would clearly be the easiest solution and would not require any additional arguments. This would also make for a straight-forward user experience. If I want only one plot, it is likely I want to focus on this and potentially customize it.
2. Add an additional argument, e.g., `as_list` which, if `TRUE`, returns the list plots as a list also skipping the `plot_grid` call. This would allow customizing even more than one plot, but the cost would of course be that the different plots would not be printed on the same window.
3. Add an additional argument, e.g., default is `return = "plot"`, but if  `return = "data"` creating the `ggplot2` object is skipped and only the data frames used for creating the plot would be returned. In this case, `draw` is only a convenience function for creating the basis for the plot and the user can create it exactly as they want.

Does any of this option sound good to you? If so, I am happy to produce a corresponding pull request (might not be instantaneous though).

**Comment by singmann** [comment] 2019-06-06 21:01
PS: The `return` argument can of course also have three levels: `plot` (default), `list` (option 2), and `data` (option 3).

**Comment by gavinsimpson** [comment] 2019-06-06 21:39
This is related to #35

**Comment by singmann** [comment] 2019-06-06 21:43
True. Sorry, I should have checked the existing issues more carefully. Anyway, I am happy to submit a pull request along the lines of #35 as well if this is what you prefer (e.g., additional `assemble` function).

**Comment by gavinsimpson** [comment] 2019-08-21 15:24
Closing this as a duplicate of #35.

**Closed by gavinsimpson** 2019-08-21 15:24 UTC
Labels: duplicate
